"use client";
import { useEffect,useState } from "react";
type Data={user:{displayName:string;email:string;avatarUrl:string|null;heartPoints:number};games:Array<{slug:string;creatorName:string;partnerName:string;playCount:number;completionCount:number;paymentStatus:string|null}>};
export default function Dashboard(){
  const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true);
  useEffect(()=>{fetch("/api/dashboard").then(async r=>{if(r.status===401){location.href="/api/auth/google?returnTo=/dashboard";return}setData(await r.json());setLoading(false)})},[]);
  if(loading)return <main className="account-page"><p>กำลังเปิดเกมของคุณ...</p></main>;if(!data)return null;
  return <main className="account-page"><header className="account-header"><a className="brand" href="/"><span className="brand-mark">♥</span><span>HEART<span>QUEST</span></span></a><div className="account-user">{data.user.avatarUrl&&<img src={data.user.avatarUrl} alt=""/>}<span><b>{data.user.displayName}</b><small>{data.user.email}</small></span><button onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});location.href='/'}}>ออกจากระบบ</button></div></header><section className="dashboard-hero"><div><p className="eyebrow">CREATOR DASHBOARD</p><h1>เกมของฉัน</h1><p>จัดการเกม ดูยอดผู้เล่น และสถานะการชำระเงินได้จากที่เดียว</p></div><a className="primary-button" href="/">＋ สร้างเกมใหม่</a></section><div className="dashboard-stats"><article><strong>{data.games.length}</strong><span>เกมทั้งหมด</span></article><article><strong>{data.games.reduce((n,g)=>n+g.playCount,0)}</strong><span>ยอดเล่น</span></article><article><strong>{data.games.reduce((n,g)=>n+g.completionCount,0)}</strong><span>เล่นจบ</span></article><article><strong>{data.user.heartPoints}</strong><span>Heart Points</span></article></div><section className="game-list">{data.games.length===0?<div className="empty-games"><span>♥</span><h2>ยังไม่มีเกมในบัญชีนี้</h2><p>สร้าง HeartQuest แรกของคุณได้ฟรี</p><a href="/" className="primary-button">เริ่มสร้างเกม</a></div>:data.games.map(g=><article className="game-row" key={g.slug}><div><small>LOVE QUEST</small><h2>{g.creatorName} → {g.partnerName}</h2><p>เล่น {g.playCount} ครั้ง · จบ {g.completionCount} ครั้ง</p></div><span className={`payment-badge ${g.paymentStatus||'free'}`}>{g.paymentStatus==='approved'?'Premium':g.paymentStatus?'กำลังตรวจสอบ':'Free'}</span><div><a href={`/q/${g.slug}`} target="_blank">เปิดเกม</a><a href={`/pay/${g.slug}`}>อัปเกรด</a></div></article>)}</section></main>
}
