"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type Stage={id:string;type:"npc"|"key"|"collect"|"quiz"|"match"|"timeline"|"catch"|"rhythm"|"ending";title:string;instruction?:string;imageUrl?:string;target?:number;speed?:"easy"|"normal"|"hard";question?:string;answer?:string;decoys?:string[]};
type Game={slug:string;creator:string;partner:string;message:string;theme:string;youtubeUrl:string|null;memories:string[];referralCode:string;occasion:string;questPlan:Stage[]};
const spots=[{x:18,y:28},{x:70,y:24},{x:48,y:58},{x:83,y:67},{x:31,y:49},{x:61,y:39},{x:9,y:42},{x:76,y:52},{x:40,y:22},{x:55,y:70}];
const fallback:Stage[]=[{id:"key",type:"key",title:"ตามหากุญแจลับ"},{id:"collect",type:"collect",title:"เก็บความทรงจำทั้งหมด"},{id:"quiz",type:"quiz",title:"คำถามวัดใจ",question:"ใครเป็นคนส่งภารกิจนี้มาให้?",answer:"ผู้สร้างเกม",decoys:["ผู้พิทักษ์หัวใจ","คนแปลกหน้าลึกลับ"]},{id:"ending",type:"ending",title:"เปิดข้อความจากหัวใจ"}];
export default function GameClient({game}:{game:Game}){
 const stages=game.questPlan.length?game.questPlan:fallback,[started,setStarted]=useState(false),[stageIndex,setStageIndex]=useState(0),stage=stages[stageIndex];
 const [pos,setPos]=useState({x:46,y:72}),[collected,setCollected]=useState<number[]>([]),[memory,setMemory]=useState<number|null>(null),[wrong,setWrong]=useState(false),[keyTry,setKeyTry]=useState<number[]>([]),[accepted,setAccepted]=useState(false),[noPos,setNoPos]=useState({x:64,y:76}),[shared,setShared]=useState(false);const keys=useRef<Record<string,boolean>>({});
 const [flipped,setFlipped]=useState<number[]>([]),[matched,setMatched]=useState<number[]>([]),[timelineStep,setTimelineStep]=useState(0),[timelineWrong,setTimelineWrong]=useState<number|null>(null),[catchScore,setCatchScore]=useState(0),[catchTarget,setCatchTarget]=useState(0),[rhythmScore,setRhythmScore]=useState(0);
 const endingCopy=game.occasion==="birthday"?{q:"พร้อมเริ่มปีใหม่ที่พิเศษไปด้วยกันไหม?",yes:"พร้อมเลย 🎂"}:game.occasion==="apology"?{q:"ให้โอกาสเราแก้ตัวและดูแลให้ดีกว่านี้ได้ไหม?",yes:"ให้โอกาส 💗"}:game.occasion==="confession"?{q:"ลองเปิดใจให้ความรู้สึกนี้ได้ไหม?",yes:"เปิดใจ 💗"}:game.occasion==="valentine"?{q:"เป็นวาเลนไทน์ของเรานะ?",yes:"ตกลง 🌹"}:{q:"ไปสร้างด่านต่อไปด้วยกันไหม?",yes:"ไปด้วยกัน 💗"};
 const next=()=>{setWrong(false);setMemory(null);setPos({x:46,y:72});if(stageIndex<stages.length-1)setStageIndex(x=>x+1);else complete()};
 const complete=()=>fetch(`/api/games/${game.slug}/events`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"complete"})}).catch(()=>{});
 useEffect(()=>{fetch(`/api/games/${game.slug}/events`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"open"})}).catch(()=>{})},[game.slug]);
 useEffect(()=>{if(!started||stage?.type!=="collect"||memory!==null)return;const down=(e:KeyboardEvent)=>{keys.current[e.key]=true},up=(e:KeyboardEvent)=>{keys.current[e.key]=false};addEventListener("keydown",down);addEventListener("keyup",up);const t=setInterval(()=>setPos(p=>({x:Math.max(4,Math.min(92,p.x+((keys.current.ArrowRight||keys.current.d)?1.5:0)-((keys.current.ArrowLeft||keys.current.a)?1.5:0))),y:Math.max(19,Math.min(78,p.y+((keys.current.ArrowDown||keys.current.s)?1.5:0)-((keys.current.ArrowUp||keys.current.w)?1.5:0)))})),30);return()=>{clearInterval(t);removeEventListener("keydown",down);removeEventListener("keyup",up)}},[started,stage?.type,memory]);
 useEffect(()=>{if(stage?.type!=="collect"||memory!==null)return;spots.slice(0,game.memories.length).forEach((h,i)=>{if(!collected.includes(i)&&Math.hypot(pos.x-h.x,pos.y-h.y)<7){setCollected(c=>[...c,i]);setMemory(i)}})},[pos,stage?.type,memory,collected,game.memories.length]);
 const move=(dx:number,dy:number)=>setPos(p=>({x:Math.max(4,Math.min(92,p.x+dx)),y:Math.max(19,Math.min(78,p.y+dy))}));
 const chooseKey=(i:number)=>{if(i===2)setTimeout(next,350);else setKeyTry(x=>[...x,i])};
 const answer=(v:string)=>{const correct=stage.answer||game.creator;if(v===correct||(correct==="ผู้สร้างเกม"&&v===game.creator))next();else setWrong(true)};
 const share=async()=>{try{if(navigator.share)await navigator.share({title:"HeartQuest",text:`ภารกิจจาก ${game.creator} ถึง ${game.partner}`,url:location.href});else await navigator.clipboard.writeText(location.href);setShared(true)}catch{}};
 const options=useMemo(()=>stage?.type==="quiz"?[...(stage.decoys||[]),stage.answer==="ผู้สร้างเกม"?game.creator:(stage.answer||game.creator)].sort((a,b)=>a.localeCompare(b)):[],[stage,game.creator]);
 const matchCards=useMemo(()=>{const source=(game.memories.length>1?game.memories:[...game.memories,"เรื่องของเรา"]).slice(0,3);return source.flatMap((text,pair)=>[{text,pair},{text,pair}]).sort((a,b)=>a.text.localeCompare(b.text))},[game.memories]);
 const timelineItems=useMemo(()=>game.memories.slice(0,6).map((text,original)=>({text,original})).sort((a,b)=>b.original-a.original),[game.memories]);
 const catchPositions=[{x:18,y:32},{x:68,y:24},{x:43,y:56},{x:76,y:64},{x:25,y:70},{x:52,y:31},{x:12,y:55},{x:82,y:42}];
 const flipCard=(index:number)=>{if(flipped.includes(index)||matched.includes(index))return;const nextFlip=[...flipped,index];setFlipped(nextFlip);if(nextFlip.length===2){const [a,b]=nextFlip;if(matchCards[a].pair===matchCards[b].pair){const done=[...matched,a,b];setMatched(done);setFlipped([]);if(done.length===matchCards.length)setTimeout(next,500)}else setTimeout(()=>setFlipped([]),650)}};
 const pickTimeline=(original:number)=>{if(original===timelineStep){const value=timelineStep+1;setTimelineStep(value);setTimelineWrong(null);if(value>=timelineItems.length)setTimeout(next,450)}else{setTimelineWrong(original);setTimeout(()=>setTimelineWrong(null),500)}};
 const catchHeart=()=>{const score=catchScore+1;setCatchScore(score);setCatchTarget((catchTarget+3)%catchPositions.length);if(score>=(stage.target||8))setTimeout(next,350)};
 const tapRhythm=()=>{const score=rhythmScore+1;setRhythmScore(score);if(score>=(stage.target||8))setTimeout(next,350)};
 if(!started)return <main className={`stage-game theme-${game.theme}`}><section className="stage-intro"><div className="quest-logo">♥</div><p className="pixel-label">HEARTQUEST STORY MODE</p><h1>{game.partner}</h1><p>{game.creator} สร้างเส้นทางพิเศษ {stages.length} ด่านไว้ให้คุณ</p><div className="route-map">{stages.map((s,i)=><div key={s.id}><span>{i+1}</span><b>{s.title}</b></div>)}</div><button className="stage-primary" onClick={()=>setStarted(true)}>เริ่มด่านแรก →</button></section></main>;
 return <main className={`stage-game theme-${game.theme} scene-${stage.type}`}><header className="stage-hud"><b>HEARTQUEST</b><div className="stage-progress">{stages.map((s,i)=><i key={s.id} className={i<stageIndex?"done":i===stageIndex?"active":""}/>)}</div><span>ด่าน {stageIndex+1}/{stages.length}</span></header>
 <div className="stage-title"><small>{stage.type.toUpperCase()} QUEST</small><h1>{stage.title||"ด่านลับ"}</h1>{stage.instruction&&<p>{stage.instruction}</p>}</div>
 {stage.imageUrl&&<div className="stage-photo"><img src={stage.imageUrl} alt="รูปประกอบความทรงจำ"/></div>}
 {game.youtubeUrl&&<a className="music-pill" href={game.youtubeUrl} target="_blank" rel="noreferrer">♫ เปิดเพลงประกอบ</a>}
 {stage.type==="npc"&&<section className="npc-scene"><div className="pixel-npc">!</div><div className="stage-dialog"><small>ผู้พิทักษ์หัวใจ</small><h2>ยินดีต้อนรับ {game.partner}</h2><p>{game.creator} ฝากเรื่องราวบางอย่างไว้ กระจายอยู่ตามเส้นทางข้างหน้า เตรียมหัวใจให้พร้อมแล้วออกเดินทางกัน</p><button onClick={next}>รับภารกิจ →</button></div></section>}
 {stage.type==="key"&&<section className="key-scene"><p>กุญแจจริงซ่อนอยู่ในหนึ่งในสามกล่อง ลองเลือกดู</p><div className="chests">{[0,1,2].map(i=><button key={i} className={keyTry.includes(i)?"empty":""} onClick={()=>chooseKey(i)} disabled={keyTry.includes(i)}><span>{keyTry.includes(i)?"💨":i===2&&keyTry.length>1?"🔑":"🎁"}</span><b>กล่อง {i+1}</b></button>)}</div>{keyTry.length>0&&<p className="stage-hint">{keyTry.includes(2)?"พบกุญแจแล้ว!":"ยังไม่ใช่ ลองอีกกล่องนะ"}</p>}</section>}
 {stage.type==="collect"&&<section className="collect-scene"><div className="collect-count">♥ {collected.length}/{game.memories.length}</div><div className="scene-moon">♥</div><div className="scene-hills"/><div className="scene-ground"/>{spots.slice(0,game.memories.length).map((h,i)=>!collected.includes(i)&&<button key={i} className="stage-heart" style={{left:`${h.x}%`,top:`${h.y}%`}} onClick={()=>{setCollected(c=>[...c,i]);setMemory(i)}}>♥</button>)}<div className="quest-player" style={{left:`${pos.x}%`,top:`${pos.y}%`}}><i/><b/></div><div className="quest-controls"><button onClick={()=>move(-4,0)}>◀</button><span><button onClick={()=>move(0,-4)}>▲</button><button onClick={()=>move(0,4)}>▼</button></span><button onClick={()=>move(4,0)}>▶</button></div>{memory!==null&&<div className="stage-dialog overlay"><small>MEMORY {memory+1}</small><h2>พบความทรงจำแล้ว!</h2><p>{game.memories[memory]}</p><button onClick={()=>{const all=collected.length>=game.memories.length;setMemory(null);if(all)next()}}>{collected.length>=game.memories.length?"ไปด่านถัดไป":"ตามหาดวงต่อไป"} →</button></div>}</section>}
 {stage.type==="quiz"&&<section className="quiz-scene"><div className="quiz-orb">?</div><h2>{stage.question||"ใครเป็นคนส่งภารกิจนี้มาให้?"}</h2><div className="quiz-grid">{options.map(o=><button key={o} onClick={()=>answer(o)}>{o}</button>)}</div>{wrong&&<p>ยังไม่ถูก ลองอีกครั้งนะ 💗</p>}</section>}
 {stage.type==="match"&&<section className="match-scene"><p className="mini-instruction">เปิดการ์ดทีละ 2 ใบ แล้วจับคู่ความทรงจำให้ครบ</p><div className="match-grid">{matchCards.map((card,i)=>{const open=flipped.includes(i)||matched.includes(i);return <button key={i} className={open?"open":""} onClick={()=>flipCard(i)} disabled={matched.includes(i)}><span>{open?card.text:"♥"}</span></button>})}</div><b className="mini-score">จับคู่แล้ว {matched.length/2}/{matchCards.length/2}</b></section>}
 {stage.type==="timeline"&&<section className="timeline-scene"><p className="mini-instruction">แตะเหตุการณ์จากอดีตมาถึงปัจจุบัน</p><div className="timeline-list">{timelineItems.map(item=><button key={item.original} className={`${item.original<timelineStep?"done":""} ${timelineWrong===item.original?"wrong":""}`} onClick={()=>pickTimeline(item.original)} disabled={item.original<timelineStep}><span>{item.original<timelineStep?"✓":"?"}</span>{item.text}</button>)}</div><b className="mini-score">ลำดับที่ {Math.min(timelineStep+1,timelineItems.length)}/{timelineItems.length}</b></section>}
 {stage.type==="catch"&&<section className={`catch-scene speed-${stage.speed||"normal"}`}><p className="mini-instruction">แตะหัวใจให้ครบ {stage.target||8} ดวง!</p><button className="catch-heart" style={{left:`${catchPositions[catchTarget].x}%`,top:`${catchPositions[catchTarget].y}%`}} onClick={catchHeart}>♥</button><div className="catch-clouds"/><b className="mini-score">หัวใจ {catchScore}/{stage.target||8}</b></section>}
 {stage.type==="rhythm"&&<section className={`rhythm-scene speed-${stage.speed||"normal"}`}><p className="mini-instruction">แตะหัวใจตามจังหวะให้ครบ {stage.target||8} ครั้ง</p><button className="rhythm-heart" onClick={tapRhythm}><span>♥</span><i/></button><div className="rhythm-dots">{Array.from({length:Math.min(stage.target||8,20)},(_,i)=><i key={i} className={i<rhythmScore?"done":""}/>)}</div><b className="mini-score">จังหวะ {rhythmScore}/{stage.target||8}</b></section>}
 {stage.type==="ending"&&<section className="ending-scene"><div className="ending-card"><div className="ending-heart">♥</div><small>QUEST COMPLETE</small><h1>ถึง {game.partner}</h1><blockquote>“{game.message}”</blockquote><p>— {game.creator}</p>{!accepted?<div className="choice-zone"><h2>{endingCopy.q}</h2><button className="yes-choice" onClick={()=>{setAccepted(true);complete()}}>{endingCopy.yes}</button><button className="no-choice" style={{left:`${noPos.x}%`,top:`${noPos.y}%`}} onMouseEnter={()=>setNoPos({x:8+Math.random()*75,y:65+Math.random()*20})} onTouchStart={()=>setNoPos({x:8+Math.random()*75,y:65+Math.random()*20})}>ยังไม่ตอบ</button></div>:<p className="accepted-message">ภารกิจรักสำเร็จ! ✨</p>}<div className="ending-actions"><button onClick={share}>{shared?"คัดลอกแล้ว ✓":"แชร์เรื่องราว"}</button><a href={`/?ref=${game.referralCode}`}>สร้างเกมของฉัน</a></div></div></section>}
 </main>
}
