"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type Stage={id:string;type:"npc"|"key"|"collect"|"quiz"|"ending";title:string;question?:string;answer?:string;decoys?:string[]};
type Game={slug:string;creator:string;partner:string;message:string;theme:string;youtubeUrl:string|null;memories:string[];referralCode:string;occasion:string;questPlan:Stage[]};
const spots=[{x:18,y:28},{x:70,y:24},{x:48,y:58},{x:83,y:67},{x:31,y:49},{x:61,y:39},{x:9,y:42},{x:76,y:52},{x:40,y:22},{x:55,y:70}];
const fallback:Stage[]=[{id:"key",type:"key",title:"ตามหากุญแจลับ"},{id:"collect",type:"collect",title:"เก็บความทรงจำทั้งหมด"},{id:"quiz",type:"quiz",title:"คำถามวัดใจ",question:"ใครเป็นคนส่งภารกิจนี้มาให้?",answer:"ผู้สร้างเกม",decoys:["ผู้พิทักษ์หัวใจ","คนแปลกหน้าลึกลับ"]},{id:"ending",type:"ending",title:"เปิดข้อความจากหัวใจ"}];
export default function GameClient({game}:{game:Game}){
 const stages=game.questPlan.length?game.questPlan:fallback,[started,setStarted]=useState(false),[stageIndex,setStageIndex]=useState(0),stage=stages[stageIndex];
 const [pos,setPos]=useState({x:46,y:72}),[collected,setCollected]=useState<number[]>([]),[memory,setMemory]=useState<number|null>(null),[wrong,setWrong]=useState(false),[keyTry,setKeyTry]=useState<number[]>([]),[accepted,setAccepted]=useState(false),[noPos,setNoPos]=useState({x:64,y:76}),[shared,setShared]=useState(false);const keys=useRef<Record<string,boolean>>({});
 const endingCopy=game.occasion==="birthday"?{q:"พร้อมเริ่มปีใหม่ที่พิเศษไปด้วยกันไหม?",yes:"พร้อมเลย 🎂"}:game.occasion==="apology"?{q:"ให้โอกาสเราแก้ตัวและดูแลให้ดีกว่านี้ได้ไหม?",yes:"ให้โอกาส 💗"}:game.occasion==="confession"?{q:"ลองเปิดใจให้ความรู้สึกนี้ได้ไหม?",yes:"เปิดใจ 💗"}:game.occasion==="valentine"?{q:"เป็นวาเลนไทน์ของเรานะ?",yes:"ตกลง 🌹"}:{q:"ไปสร้างด่านต่อไปด้วยกันไหม?",yes:"ไปด้วยกัน 💗"};
 const next=()=>{setWrong(false);setMemory(null);setPos({x:46,y:72});if(stageIndex<stages.length-1)setStageIndex(x=>x+1);else complete()};
 const complete=()=>fetch(`/api/games/${game.slug}/events`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"complete"})}).catch(()=>{});
 useEffect(()=>{fetch(`/api/games/${game.slug}/events`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({event:"open"})}).catch(()=>{})},[game.slug]);
 useEffect(()=>{if(!started||stage?.type!=="collect"||memory!==null)return;const down=(e:KeyboardEvent)=>{keys.current[e.key]=true},up=(e:KeyboardEvent)=>{keys.current[e.key]=false};addEventListener("keydown",down);addEventListener("keyup",up);const t=setInterval(()=>setPos(p=>({x:Math.max(4,Math.min(92,p.x+((keys.current.ArrowRight||keys.current.d)?1.5:0)-((keys.current.ArrowLeft||keys.current.a)?1.5:0))),y:Math.max(19,Math.min(78,p.y+((keys.current.ArrowDown||keys.current.s)?1.5:0)-((keys.current.ArrowUp||keys.current.w)?1.5:0)))})),30);return()=>{clearInterval(t);removeEventListener("keydown",down);removeEventListener("keyup",up)}},[started,stage?.type,memory]);
 useEffect(()=>{if(stage?.type!=="collect"||memory!==null)return;spots.slice(0,game.memories.length).forEach((h,i)=>{if(!collected.includes(i)&&Math.hypot(pos.x-h.x,pos.y-h.y)<7){setCollected(c=>[...c,i]);setMemory(i)}})},[pos,stage?.type,memory,collected,game.memories.length]);
 const move=(dx:number,dy:number)=>setPos(p=>({x:Math.max(4,Math.min(92,p.x+dx)),y:Math.max(19,Math.min(78,p.y+dy))}));
 const chooseKey=(i:number)=>{if(i===2)setTimeout(next,350);else setKeyTry(x=>[...x,i])};
 const answer=(v:string)=>{const correct=stage.answer||game.creator;if(v===correct||(correct==="ผู้สร้างเกม"&&v===game.creator))next();else setWrong(true)};
 const share=async()=>{try{if(navigator.share)await navigator.share({title:"HeartQuest",text:`ภารกิจจาก ${game.creator} ถึง ${game.partner}`,url:location.href});else await navigator.clipboard.writeText(location.href);setShared(true)}catch{}};
 const options=useMemo(()=>stage?.type==="quiz"?[...(stage.decoys||[]),stage.answer==="ผู้สร้างเกม"?game.creator:(stage.answer||game.creator)].sort((a,b)=>a.localeCompare(b)):[],[stage,game.creator]);
 if(!started)return <main className={`stage-game theme-${game.theme}`}><section className="stage-intro"><div className="quest-logo">♥</div><p className="pixel-label">HEARTQUEST STORY MODE</p><h1>{game.partner}</h1><p>{game.creator} สร้างเส้นทางพิเศษ {stages.length} ด่านไว้ให้คุณ</p><div className="route-map">{stages.map((s,i)=><div key={s.id}><span>{i+1}</span><b>{s.title}</b></div>)}</div><button className="stage-primary" onClick={()=>setStarted(true)}>เริ่มด่านแรก →</button></section></main>;
 return <main className={`stage-game theme-${game.theme} scene-${stage.type}`}><header className="stage-hud"><b>HEARTQUEST</b><div className="stage-progress">{stages.map((s,i)=><i key={s.id} className={i<stageIndex?"done":i===stageIndex?"active":""}/>)}</div><span>ด่าน {stageIndex+1}/{stages.length}</span></header>
 <div className="stage-title"><small>{stage.type.toUpperCase()} QUEST</small><h1>{stage.title}</h1></div>
 {game.youtubeUrl&&<a className="music-pill" href={game.youtubeUrl} target="_blank" rel="noreferrer">♫ เปิดเพลงประกอบ</a>}
 {stage.type==="npc"&&<section className="npc-scene"><div className="pixel-npc">!</div><div className="stage-dialog"><small>ผู้พิทักษ์หัวใจ</small><h2>ยินดีต้อนรับ {game.partner}</h2><p>{game.creator} ฝากเรื่องราวบางอย่างไว้ กระจายอยู่ตามเส้นทางข้างหน้า เตรียมหัวใจให้พร้อมแล้วออกเดินทางกัน</p><button onClick={next}>รับภารกิจ →</button></div></section>}
 {stage.type==="key"&&<section className="key-scene"><p>กุญแจจริงซ่อนอยู่ในหนึ่งในสามกล่อง ลองเลือกดู</p><div className="chests">{[0,1,2].map(i=><button key={i} className={keyTry.includes(i)?"empty":""} onClick={()=>chooseKey(i)} disabled={keyTry.includes(i)}><span>{keyTry.includes(i)?"💨":i===2&&keyTry.length>1?"🔑":"🎁"}</span><b>กล่อง {i+1}</b></button>)}</div>{keyTry.length>0&&<p className="stage-hint">{keyTry.includes(2)?"พบกุญแจแล้ว!":"ยังไม่ใช่ ลองอีกกล่องนะ"}</p>}</section>}
 {stage.type==="collect"&&<section className="collect-scene"><div className="collect-count">♥ {collected.length}/{game.memories.length}</div><div className="scene-moon">♥</div><div className="scene-hills"/><div className="scene-ground"/>{spots.slice(0,game.memories.length).map((h,i)=>!collected.includes(i)&&<button key={i} className="stage-heart" style={{left:`${h.x}%`,top:`${h.y}%`}} onClick={()=>{setCollected(c=>[...c,i]);setMemory(i)}}>♥</button>)}<div className="quest-player" style={{left:`${pos.x}%`,top:`${pos.y}%`}}><i/><b/></div><div className="quest-controls"><button onClick={()=>move(-4,0)}>◀</button><span><button onClick={()=>move(0,-4)}>▲</button><button onClick={()=>move(0,4)}>▼</button></span><button onClick={()=>move(4,0)}>▶</button></div>{memory!==null&&<div className="stage-dialog overlay"><small>MEMORY {memory+1}</small><h2>พบความทรงจำแล้ว!</h2><p>{game.memories[memory]}</p><button onClick={()=>{const all=collected.length>=game.memories.length;setMemory(null);if(all)next()}}>{collected.length>=game.memories.length?"ไปด่านถัดไป":"ตามหาดวงต่อไป"} →</button></div>}</section>}
 {stage.type==="quiz"&&<section className="quiz-scene"><div className="quiz-orb">?</div><h2>{stage.question||"ใครเป็นคนส่งภารกิจนี้มาให้?"}</h2><div className="quiz-grid">{options.map(o=><button key={o} onClick={()=>answer(o)}>{o}</button>)}</div>{wrong&&<p>ยังไม่ถูก ลองอีกครั้งนะ 💗</p>}</section>}
 {stage.type==="ending"&&<section className="ending-scene"><div className="ending-card"><div className="ending-heart">♥</div><small>QUEST COMPLETE</small><h1>ถึง {game.partner}</h1><blockquote>“{game.message}”</blockquote><p>— {game.creator}</p>{!accepted?<div className="choice-zone"><h2>{endingCopy.q}</h2><button className="yes-choice" onClick={()=>{setAccepted(true);complete()}}>{endingCopy.yes}</button><button className="no-choice" style={{left:`${noPos.x}%`,top:`${noPos.y}%`}} onMouseEnter={()=>setNoPos({x:8+Math.random()*75,y:65+Math.random()*20})} onTouchStart={()=>setNoPos({x:8+Math.random()*75,y:65+Math.random()*20})}>ยังไม่ตอบ</button></div>:<p className="accepted-message">ภารกิจรักสำเร็จ! ✨</p>}<div className="ending-actions"><button onClick={share}>{shared?"คัดลอกแล้ว ✓":"แชร์เรื่องราว"}</button><a href={`/?ref=${game.referralCode}`}>สร้างเกมของฉัน</a></div></div></section>}
 </main>
}
